export enum FactoryType {
  Actor = 'actor_factory',
  Camera = 'camera_factory',
  Controls = 'controls_factory',
  EnvMap = 'env_map_factory',
  Fog = 'fog_factory',
  IntersectionsWatcher = 'intersections_watcher_factory',
  Light = 'light_factory',
  Material = 'material_factory',
  MouseClickWatcher = 'mouse_click_watcher_factory',
  Models3d = 'models_3d_factory',
  MousePositionWatcher = 'mouse_position_watcher_factory',
  Particles = 'particles_factory',
  PhysicsBody = 'physics_body_factory',
  PhysicsPreset = 'physics_preset_factory',
  Renderer = 'renderer_factory',
  Scene = 'scene_factory',
  ScreenSizeWatcher = 'screen_size_watcher_factory',
  SpatialGrid = 'spatial_grid_factory',
  Text = 'text_factory',
  Texture = 'texture_factory'
}
