export enum RegistryType {
  Actor = 'actor',
  Camera = 'camera',
  Controls = 'controls',
  EnvMap = 'env_map',
  EnvMapTexture = 'env_map_texture',
  Fog = 'fog',
  IntersectionsWatcher = 'intersections_watcher',
  KeyboardRecord = 'keyboard_record',
  Light = 'light',
  Material = 'material',
  Model3d = 'model_3d',
  Model3dAnimations = 'model_3d_animations',
  MouseClickWatcher = 'mouse_click_watcher',
  MousePositionWatcher = 'mouse_position_watcher',
  Particles = 'particles',
  PhysicsPreset = 'physics_preset',
  PhysicsBody = 'physics_body',
  Renderer = 'renderer',
  Scene = 'scene',
  ScreenSizeWatcher = 'screen_size_watcher',
  SpatialGrid = 'spatial_grid',
  Text = 'text',
  TextRenderer = 'text_renderer',
  Texture = 'texture'
}
