export enum WrapperType {
  Actor = 'actor_wrapper',
  AmbientLight = 'ambient_light_wrapper',
  Camera = 'camera_wrapper',
  Color = 'color_wrapper',
  Controls = 'controls_wrapper',
  DirectionalLight = 'directional_light_wrapper',
  Euler = 'euler_wrapper',
  Fog = 'fog_wrapper',
  HemisphereLight = 'hemisphere_light_wrapper',
  Material = 'material_wrapper',
  Particles = 'particles_wrapper',
  PointLight = 'point_light_wrapper',
  Physics = 'physics_wrapper',
  RectAreaLight = 'rect_area_light_wrapper',
  Renderer = 'renderer_wrapper',
  Scene = 'scene_wrapper',
  SpotLight = 'spot_light_wrapper',
  SpatialGrid = 'spatial_grid_wrapper',
  Text2d = 'text2d_wrapper',
  Text3d = 'text3d_wrapper',
  Texture = 'texture_wrapper',
  Vector2 = 'vector2_wrapper',
  Vector3 = 'vector3_wrapper',
  Vector4 = 'vector4_wrapper'
}
