import type { TActorService } from '@/Engine/Actor';
import type { TAnimationsService } from '@/Engine/Animations';
import type { TAudioService } from '@/Engine/Audio';
import type { TCameraService } from '@/Engine/Camera';
import type { TCollisionsService } from '@/Engine/Collisions';
import type { TControlsService } from '@/Engine/Controls';
import type { TEnvMapService } from '@/Engine/EnvMap';
import type { TFogService } from '@/Engine/Fog';
import type { TFsmService } from '@/Engine/Fsm';
import type { TIntersectionsWatcherService } from '@/Engine/Intersections';
import type { TLightService } from '@/Engine/Light';
import type { TLoopService } from '@/Engine/Loop';
import type { TMaterialService } from '@/Engine/Material';
import type { TModels3dService } from '@/Engine/Models3d';
import type { TMouseService } from '@/Engine/Mouse';
import type { TParticlesService } from '@/Engine/Particles';
import type { TPhysicsBodyService, TPhysicsPresetsService, TPhysicsWorldService } from '@/Engine/Physics';
import type { TRendererService } from '@/Engine/Renderer';
import type { TScenesService } from '@/Engine/Scene';
import type { TSpatialGridService } from '@/Engine/Spatial';
import type { TTextService } from '@/Engine/Text';
import type { TTextureService } from '@/Engine/Texture';

export type TSpaceServices = Readonly<{
  actorService: TActorService;
  audioService: TAudioService;
  cameraService: TCameraService;
  controlsService: TControlsService;
  collisionsService: TCollisionsService;
  envMapService: TEnvMapService;
  fogService: TFogService;
  fsmService: TFsmService;
  intersectionsWatcherService: TIntersectionsWatcherService;
  lightService: TLightService;
  loopService: TLoopService;
  materialService: TMaterialService;
  models3dService: TModels3dService;
  animationsService: TAnimationsService;
  mouseService: TMouseService;
  particlesService: TParticlesService;
  physicsBodyService: TPhysicsBodyService;
  physicsWorldService: TPhysicsWorldService;
  physicsPresetService: TPhysicsPresetsService;
  rendererService: TRendererService;
  scenesService: TScenesService;
  spatialGridService: TSpatialGridService;
  textService: TTextService;
  textureService: TTextureService;
}>;
