import type { TActorService } from '@/Engine/Actor';
import type { TCameraService } from '@/Engine/Camera';
import type { TControlsService } from '@/Engine/Controls';
import type { TEnvMapService } from '@/Engine/EnvMap';
import type { TFogService } from '@/Engine/Fog';
import type { TIntersectionsWatcherService } from '@/Engine/Intersections';
import type { TLightService } from '@/Engine/Light';
import type { TLoopService } from '@/Engine/Loop';
import type { TMaterialService } from '@/Engine/Material';
import type { TMaterialTextureService } from '@/Engine/MaterialTexturePack';
import type { TParticlesService } from '@/Engine/Particles';
import type { TPhysicsBodyService, TPhysicsPresetsService } from '@/Engine/Physics';
import type { TRendererService } from '@/Engine/Renderer';
import type { TScenesService } from '@/Engine/Scene';
import type { TTextService } from '@/Engine/Text';

export type TSpaceServices = Readonly<{
  actorService: TActorService;
  cameraService: TCameraService;
  controlsService: TControlsService;
  envMapService: TEnvMapService;
  fogService: TFogService;
  intersectionsWatcherService: TIntersectionsWatcherService;
  lightService: TLightService;
  loopService: TLoopService;
  materialService: TMaterialService;
  materialTextureService: TMaterialTextureService;
  particlesService: TParticlesService;
  physicsBodyService: TPhysicsBodyService;
  physicsPresetService: TPhysicsPresetsService;
  rendererService: TRendererService;
  scenesService: TScenesService;
  textService: TTextService;
}>;
