export * from './IWithCoordsXY';
export * from './IWithCoordsXYZ';
export * from './IWithCoordsXYZW';
export * from './IWithCoordsXZ';
export * from './IWithCoordsYZ';
export * from './IWithCoordW';
export * from './IWithCoordX';
export * from './IWithCoordY';
export * from './IWithCoordZ';
