import type { Color, MeshBasicMaterial, MeshStandardMaterial } from 'three';

import type { TextAlign, TextAnchorX, TextAnchorY, TextDirection, TextFontStyle, TextFontWeight, TextOverflowWrap, TextWhiteSpace } from '@/Engine/Domains/Text';
import type { IMovable, IRotatable } from '@/Engine/Mixins';

export type ITextAccessors = IMovable &
  IRotatable &
  Readonly<{
    setText: (text: string) => void;
    getText: () => string;
    setFontSize: (fontSize: number) => void;
    getFontSize: () => number;
    setColor: (color: string | number | Color) => void;
    getColor: () => string | number | Color;
    setFont: (font: string) => void;
    getFont: () => string;
    setMaxWidth: (maxWidth: number) => void;
    getMaxWidth: () => number;
    setLineHeight: (lineHeight: number) => void;
    getLineHeight: () => number;
    setLetterSpacing: (letterSpacing: number) => void;
    getLetterSpacing: () => number;
    setTextAlign: (textAlign: TextAlign) => void;
    getTextAlign: () => TextAlign;
    setMaterial: (material: MeshBasicMaterial | MeshStandardMaterial) => void;
    getMaterial: () => MeshBasicMaterial | MeshStandardMaterial;
    setAnchorX: (anchorX: TextAnchorX | number) => void;
    getAnchorX: () => TextAnchorX | number;
    setAnchorY: (anchorY: TextAnchorY | number) => void;
    getAnchorY: () => TextAnchorY | number;
    setClipRect: (clipRect: [number, number, number, number]) => void;
    getClipRect: () => [number, number, number, number];
    setDepthOffset: (depthOffset: number) => void;
    getDepthOffset: () => number;
    setDirection: (direction: TextDirection) => void;
    getDirection: () => TextDirection;
    setOverflowWrap: (overflowWrap: TextOverflowWrap) => void;
    getOverflowWrap: () => TextOverflowWrap;
    setWhiteSpace: (whiteSpace: TextWhiteSpace) => void;
    getWhiteSpace: () => TextWhiteSpace;
    setOutlineWidth: (outlineWidth: number) => void;
    getOutlineWidth: () => number;
    setOutlineOffsetX: (outlineOffsetX: number) => void;
    getOutlineOffsetX: () => number;
    setOutlineOffsetY: (outlineOffsetY: number) => void;
    getOutlineOffsetY: () => number;
    setOutlineColor: (outlineColor: string | number) => void;
    getOutlineColor: () => string | number;
    setOutlineOpacity: (outlineOpacity: number) => void;
    getOutlineOpacity: () => number;
    setStrokeWidth: (strokeWidth: number) => void;
    getStrokeWidth: () => number;
    setStrokeColor: (strokeColor: string | number | Color) => void;
    getStrokeColor: () => string | number | Color;
    setStrokeOpacity: (strokeOpacity: number) => void;
    getStrokeOpacity: () => number;
    setCurveRadius: (curveRadius: number) => void;
    getCurveRadius: () => number;
    setFillOpacity: (fillOpacity: number) => void;
    getFillOpacity: () => number;
    setFontStyle: (fontStyle: TextFontStyle) => void;
    getFontStyle: () => TextFontStyle;
    setFontWeight: (fontWeight: TextFontWeight) => void;
    getFontWeight: () => TextFontWeight;
    setGlyphGeometryDetail: (glyphGeometryDetail: number) => void;
    getGlyphGeometryDetail: () => number;
    setGpuAccelerateSDF: (gpuAccelerateSDF: boolean) => void;
    getGpuAccelerateSDF: () => boolean;
    setOutlineBlur: (outlineBlur: number) => void;
    getOutlineBlur: () => number;
    setSdfGlyphSize: (sdfGlyphSize: number) => void;
    getSdfGlyphSize: () => number;
    setTextIndent: (textIndent: number) => void;
    getTextIndent: () => number;
    setUnicodeFontsUrl: (unicodeFontsUrl: string) => void;
    getUnicodeFontsUrl: () => string;
    dispose: () => void;
    update: () => void;
  }>;
