export * from './TWithCoordsXY';
export * from './TWithCoordsXYZ';
export * from './TWithCoordsXYZW';
export * from './TWithCoordsXZ';
export * from './TWithCoordsYZ';
export * from './TWithCoordW';
export * from './TWithCoordX';
export * from './TWithCoordY';
export * from './TWithCoordZ';
