import { writeFileSync, existsSync, readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const cwd = process.cwd();

const args = process.argv.slice(2);
const pkgArg = args.find((arg) => arg.startsWith('--pkg='));
const outArg = args.find((arg) => arg.startsWith('--out='));

const pkgPath = pkgArg ? resolve(cwd, pkgArg.split('=')[1]) : resolve(cwd, 'package.json');

const outPath = outArg ? resolve(cwd, outArg.split('=')[1]) : resolve(cwd, './versions.ts');

if (!existsSync(pkgPath)) {
  console.error(`❌ package.json not found at: ${pkgPath}`);
  process.exit(1);
}

const raw = readFileSync(pkgPath, 'utf8');
let version;

try {
  const pkg = JSON.parse(raw);
  version = pkg.version;
} catch (err) {
  console.error(`❌ Failed to parse package.json:`, err);
  process.exit(1);
}

if (!version) {
  console.error(`❌ "version" field not found in ${pkgPath}`);
  process.exit(1);
}

const content = `// This file is auto-generated by GenerateVersionsFile.js
// Do not edit manually. Run the script to update.

export const packageJsonVersion = '${version}';\n`;
writeFileSync(outPath, content, 'utf8');

console.log(`✅ version.ts generated at: ${outPath}`);
console.log(`📦 version: ${version}`);
