export type TLegalDocumentType =
  | 'DISCLAIMER'
  | 'EULA'
  | 'EU_DECLARATION_OF_CONFORMITY'
  | 'INSTRUCTIONS'
  | 'PRIVACY'
  | 'SECURITY'
  | 'SUPPORT'
  | 'TECHNICAL_DOCUMENTATION'
  | 'VULN_HANDLING'
  | 'NOTICE'
  | string;
