import type { TActorService } from '@Anarchy/Engine/Actor';
import type { TAnimationsService } from '@Anarchy/Engine/Animations';
import type { TAudioService } from '@Anarchy/Engine/Audio';
import type { TCameraService } from '@Anarchy/Engine/Camera';
import type { TCollisionsService } from '@Anarchy/Engine/Collisions';
import type { TControlsService } from '@Anarchy/Engine/Controls';
import type { TEnvMapService } from '@Anarchy/Engine/EnvMap';
import type { TFogService } from '@Anarchy/Engine/Fog';
import type { TFsmService } from '@Anarchy/Engine/Fsm';
import type { TIntersectionsWatcherService } from '@Anarchy/Engine/Intersections';
import type { TKeyboardService } from '@Anarchy/Engine/Keyboard';
import type { TLightService } from '@Anarchy/Engine/Light';
import type { TLoadingManagerService } from '@Anarchy/Engine/LoadingManager';
import type { TLoopService } from '@Anarchy/Engine/Loop';
import type { TMaterialService } from '@Anarchy/Engine/Material';
import type { TModels3dService } from '@Anarchy/Engine/Models3d';
import type { TMouseService } from '@Anarchy/Engine/Mouse';
import type { TParticlesService } from '@Anarchy/Engine/Particles';
import type { TPhysicsBodyService, TPhysicsWorldService } from '@Anarchy/Engine/Physics';
import type { TRendererService } from '@Anarchy/Engine/Renderer';
import type { TScenesService } from '@Anarchy/Engine/Scene';
import type { TSpatialGridService } from '@Anarchy/Engine/Spatial';
import type { TTextService } from '@Anarchy/Engine/Text';
import type { TTextureService } from '@Anarchy/Engine/Texture';
import type { TTransformDriveService } from '@Anarchy/Engine/TransformDrive';

export type TSpaceServices = Readonly<{
  actorService: TActorService;
  animationsService: TAnimationsService;
  audioService: TAudioService;
  cameraService: TCameraService;
  collisionsService: TCollisionsService;
  controlsService: TControlsService;
  envMapService: TEnvMapService;
  fogService: TFogService;
  fsmService: TFsmService;
  intersectionsWatcherService: TIntersectionsWatcherService;
  keyboardService: TKeyboardService;
  lightService: TLightService;
  loadingManagerService: TLoadingManagerService;
  loopService: TLoopService;
  materialService: TMaterialService;
  models3dService: TModels3dService;
  mouseService: TMouseService;
  particlesService: TParticlesService;
  physicsBodyService: TPhysicsBodyService;
  physicsWorldService: TPhysicsWorldService;
  rendererService: TRendererService;
  scenesService: TScenesService;
  spatialGridService: TSpatialGridService;
  textService: TTextService;
  textureService: TTextureService;
  transformDriveService: TTransformDriveService;
}>;
