import type { TActorConfig } from '@Anarchy/Engine/Actor';
import type { TAnyAudioConfig } from '@Anarchy/Engine/Audio';
import type { TAnyCameraConfig } from '@Anarchy/Engine/Camera';
import type { TControlsConfig } from '@Anarchy/Engine/Controls';
import type { TEnvMapConfig } from '@Anarchy/Engine/EnvMap';
import type { TFogConfig } from '@Anarchy/Engine/Fog';
import type { TFsmConfig } from '@Anarchy/Engine/Fsm';
import type { TAnyIntersectionsWatcherConfig } from '@Anarchy/Engine/Intersections';
import type { TAnyLightConfig } from '@Anarchy/Engine/Light';
import type { TMaterialConfig } from '@Anarchy/Engine/Material';
import type { TModel3dConfig } from '@Anarchy/Engine/Models3d';
import type { TParticlesConfig } from '@Anarchy/Engine/Particles';
import type { TPhysicsConfig } from '@Anarchy/Engine/Physics';
import type { TRendererConfig } from '@Anarchy/Engine/Renderer';
import type { TSpatialGridConfig } from '@Anarchy/Engine/Spatial';
import type { TTextConfig } from '@Anarchy/Engine/Text';

export type TSpaceConfigEntities = Readonly<{
  spatialGrids: ReadonlyArray<TSpatialGridConfig>;
  actors: ReadonlyArray<TActorConfig>;
  audio: ReadonlyArray<TAnyAudioConfig>;
  cameras: ReadonlyArray<TAnyCameraConfig>;
  envMaps: ReadonlyArray<TEnvMapConfig>;
  intersections: ReadonlyArray<TAnyIntersectionsWatcherConfig>;
  lights: ReadonlyArray<TAnyLightConfig>;
  materials: ReadonlyArray<TMaterialConfig>;
  models3d: ReadonlyArray<TModel3dConfig>;
  renderers: ReadonlyArray<TRendererConfig>;
  particles: ReadonlyArray<TParticlesConfig>;
  physics: TPhysicsConfig;
  fogs: ReadonlyArray<TFogConfig>;
  fsm: ReadonlyArray<TFsmConfig>;
  texts: ReadonlyArray<TTextConfig>;
  controls: ReadonlyArray<TControlsConfig>;
}>;
