import type { TActorService } from '@hellpig/anarchy-engine/Actor';
import type { TAnimationsService } from '@hellpig/anarchy-engine/Animations';
import type { TAudioService } from '@hellpig/anarchy-engine/Audio';
import type { TCameraService } from '@hellpig/anarchy-engine/Camera';
import type { TCollisionsService } from '@hellpig/anarchy-engine/Collisions';
import type { TControlsService } from '@hellpig/anarchy-engine/Controls';
import type { TEnvMapService } from '@hellpig/anarchy-engine/EnvMap';
import type { TFogService } from '@hellpig/anarchy-engine/Fog';
import type { TFsmService } from '@hellpig/anarchy-engine/Fsm';
import type { TIntersectionsWatcherService } from '@hellpig/anarchy-engine/Intersections';
import type { TKeyboardService } from '@hellpig/anarchy-engine/Keyboard';
import type { TLightService } from '@hellpig/anarchy-engine/Light';
import type { TLoadingManagerService } from '@hellpig/anarchy-engine/LoadingManager';
import type { TLoopService } from '@hellpig/anarchy-engine/Loop';
import type { TMaterialService } from '@hellpig/anarchy-engine/Material';
import type { TModels3dService } from '@hellpig/anarchy-engine/Models3d';
import type { TMouseService } from '@hellpig/anarchy-engine/Mouse';
import type { TParticlesService } from '@hellpig/anarchy-engine/Particles';
import type { TPhysicsBodyService, TPhysicsWorldService } from '@hellpig/anarchy-engine/Physics';
import type { TRendererService } from '@hellpig/anarchy-engine/Renderer';
import type { TScenesService } from '@hellpig/anarchy-engine/Scene';
import type { TSpatialGridService } from '@hellpig/anarchy-engine/Spatial';
import type { TTextService } from '@hellpig/anarchy-engine/Text';
import type { TTextureService } from '@hellpig/anarchy-engine/Texture';
import type { TTransformDriveService } from '@hellpig/anarchy-engine/TransformDrive';

export type TSpaceServices = Readonly<{
  actorService: TActorService;
  animationsService: TAnimationsService;
  audioService: TAudioService;
  cameraService: TCameraService;
  collisionsService: TCollisionsService;
  controlsService: TControlsService;
  envMapService: TEnvMapService;
  fogService: TFogService;
  fsmService: TFsmService;
  intersectionsWatcherService: TIntersectionsWatcherService;
  keyboardService: TKeyboardService;
  lightService: TLightService;
  loadingManagerService: TLoadingManagerService;
  loopService: TLoopService;
  materialService: TMaterialService;
  models3dService: TModels3dService;
  mouseService: TMouseService;
  particlesService: TParticlesService;
  physicsBodyService: TPhysicsBodyService;
  physicsWorldService: TPhysicsWorldService;
  rendererService: TRendererService;
  scenesService: TScenesService;
  spatialGridService: TSpatialGridService;
  textService: TTextService;
  textureService: TTextureService;
  transformDriveService: TTransformDriveService;
}>;
