import type { TActorParams } from '@hellpig/anarchy-engine/Actor';
import type { TAnyAudioParams } from '@hellpig/anarchy-engine/Audio';
import type { TAnyCameraParams } from '@hellpig/anarchy-engine/Camera';
import type { TControlsParams } from '@hellpig/anarchy-engine/Controls';
import type { TEnvMapParams } from '@hellpig/anarchy-engine/EnvMap';
import type { TFogParams } from '@hellpig/anarchy-engine/Fog';
import type { TFsmParams } from '@hellpig/anarchy-engine/Fsm';
import type { TAnyIntersectionsWatcherParams } from '@hellpig/anarchy-engine/Intersections';
import type { TAnyLightParams } from '@hellpig/anarchy-engine/Light';
import type { TMaterialParams } from '@hellpig/anarchy-engine/Material';
import type { TModel3dParams } from '@hellpig/anarchy-engine/Models3d';
import type { TParticlesParams } from '@hellpig/anarchy-engine/Particles';
import type { TPhysicsParams } from '@hellpig/anarchy-engine/Physics';
import type { TRendererParams } from '@hellpig/anarchy-engine/Renderer';
import type { TSpatialGridParams } from '@hellpig/anarchy-engine/Spatial';
import type { TTextParams } from '@hellpig/anarchy-engine/Text';

export type TSpaceParamsEntities = Readonly<{
  actors?: ReadonlyArray<TActorParams>;
  audio?: ReadonlyArray<TAnyAudioParams>;
  cameras?: ReadonlyArray<TAnyCameraParams>;
  controls?: ReadonlyArray<TControlsParams>;
  envMaps?: ReadonlyArray<TEnvMapParams>;
  fogs?: ReadonlyArray<TFogParams>;
  fsm?: ReadonlyArray<TFsmParams>;
  intersections?: ReadonlyArray<TAnyIntersectionsWatcherParams>;
  lights?: ReadonlyArray<TAnyLightParams>;
  materials?: ReadonlyArray<TMaterialParams>;
  models3d?: ReadonlyArray<TModel3dParams>;
  renderers?: ReadonlyArray<TRendererParams>;
  particles?: ReadonlyArray<TParticlesParams>;
  physics?: TPhysicsParams;
  spatialGrids?: ReadonlyArray<TSpatialGridParams>;
  texts?: ReadonlyArray<TTextParams>;
}>;
