import type { TActorParams } from '@Anarchy/Engine/Actor';
import type { TAnyAudioParams } from '@Anarchy/Engine/Audio';
import type { TAnyCameraParams } from '@Anarchy/Engine/Camera';
import type { TControlsParams } from '@Anarchy/Engine/Controls';
import type { TEnvMapParams } from '@Anarchy/Engine/EnvMap';
import type { TFogParams } from '@Anarchy/Engine/Fog';
import type { TFsmParams } from '@Anarchy/Engine/Fsm';
import type { TAnyIntersectionsWatcherParams } from '@Anarchy/Engine/Intersections';
import type { TAnyLightParams } from '@Anarchy/Engine/Light';
import type { TMaterialParams } from '@Anarchy/Engine/Material';
import type { TModel3dParams } from '@Anarchy/Engine/Models3d';
import type { TParticlesParams } from '@Anarchy/Engine/Particles';
import type { TPhysicsParams } from '@Anarchy/Engine/Physics';
import type { TRendererParams } from '@Anarchy/Engine/Renderer';
import type { TSpatialGridParams } from '@Anarchy/Engine/Spatial';
import type { TTextParams } from '@Anarchy/Engine/Text';

export type TSpaceParamsEntities = Readonly<{
  actors?: ReadonlyArray<TActorParams>;
  audio?: ReadonlyArray<TAnyAudioParams>;
  cameras?: ReadonlyArray<TAnyCameraParams>;
  controls?: ReadonlyArray<TControlsParams>;
  envMaps?: ReadonlyArray<TEnvMapParams>;
  fogs?: ReadonlyArray<TFogParams>;
  fsm?: ReadonlyArray<TFsmParams>;
  intersections?: ReadonlyArray<TAnyIntersectionsWatcherParams>;
  lights?: ReadonlyArray<TAnyLightParams>;
  materials?: ReadonlyArray<TMaterialParams>;
  models3d?: ReadonlyArray<TModel3dParams>;
  renderers?: ReadonlyArray<TRendererParams>;
  particles?: ReadonlyArray<TParticlesParams>;
  physics?: TPhysicsParams;
  spatialGrids?: ReadonlyArray<TSpatialGridParams>;
  texts?: ReadonlyArray<TTextParams>;
}>;
