import type { TActorConfig } from '@hellpig/anarchy-engine/Actor';
import type { TAnyAudioConfig } from '@hellpig/anarchy-engine/Audio';
import type { TAnyCameraConfig } from '@hellpig/anarchy-engine/Camera';
import type { TControlsConfig } from '@hellpig/anarchy-engine/Controls';
import type { TEnvMapConfig } from '@hellpig/anarchy-engine/EnvMap';
import type { TFogConfig } from '@hellpig/anarchy-engine/Fog';
import type { TFsmConfig } from '@hellpig/anarchy-engine/Fsm';
import type { TAnyIntersectionsWatcherConfig } from '@hellpig/anarchy-engine/Intersections';
import type { TAnyLightConfig } from '@hellpig/anarchy-engine/Light';
import type { TMaterialConfig } from '@hellpig/anarchy-engine/Material';
import type { TModel3dConfig } from '@hellpig/anarchy-engine/Models3d';
import type { TParticlesConfig } from '@hellpig/anarchy-engine/Particles';
import type { TPhysicsConfig } from '@hellpig/anarchy-engine/Physics';
import type { TRendererConfig } from '@hellpig/anarchy-engine/Renderer';
import type { TSpatialGridConfig } from '@hellpig/anarchy-engine/Spatial';
import type { TTextConfig } from '@hellpig/anarchy-engine/Text';

export type TSpaceConfigEntities = Readonly<{
  spatialGrids: ReadonlyArray<TSpatialGridConfig>;
  actors: ReadonlyArray<TActorConfig>;
  audio: ReadonlyArray<TAnyAudioConfig>;
  cameras: ReadonlyArray<TAnyCameraConfig>;
  envMaps: ReadonlyArray<TEnvMapConfig>;
  intersections: ReadonlyArray<TAnyIntersectionsWatcherConfig>;
  lights: ReadonlyArray<TAnyLightConfig>;
  materials: ReadonlyArray<TMaterialConfig>;
  models3d: ReadonlyArray<TModel3dConfig>;
  renderers: ReadonlyArray<TRendererConfig>;
  particles: ReadonlyArray<TParticlesConfig>;
  physics: TPhysicsConfig;
  fogs: ReadonlyArray<TFogConfig>;
  fsm: ReadonlyArray<TFsmConfig>;
  texts: ReadonlyArray<TTextConfig>;
  controls: ReadonlyArray<TControlsConfig>;
}>;
