import type { TActorParams } from '@/Actor';
import type { TAnyAudioParams } from '@/Audio';
import type { TAnyCameraParams } from '@/Camera';
import type { TControlsParams } from '@/Controls';
import type { TEnvMapParams } from '@/EnvMap';
import type { TFogParams } from '@/Fog';
import type { TFsmParams } from '@/Fsm';
import type { TAnyIntersectionsWatcherParams } from '@/Intersections';
import type { TAnyLightParams } from '@/Light';
import type { TMaterialParams } from '@/Material';
import type { TModel3dParams } from '@/Models3d';
import type { TParticlesParams } from '@/Particles';
import type { TPhysicsParams } from '@/Physics';
import type { TRendererParams } from '@/Renderer';
import type { TSpatialGridParams } from '@/Spatial';
import type { TTextParams } from '@/Text';

export type TSpaceParamsEntities = Readonly<{
  actors?: ReadonlyArray<TActorParams>;
  audio?: ReadonlyArray<TAnyAudioParams>;
  cameras?: ReadonlyArray<TAnyCameraParams>;
  controls?: ReadonlyArray<TControlsParams>;
  envMaps?: ReadonlyArray<TEnvMapParams>;
  fogs?: ReadonlyArray<TFogParams>;
  fsm?: ReadonlyArray<TFsmParams>;
  intersections?: ReadonlyArray<TAnyIntersectionsWatcherParams>;
  lights?: ReadonlyArray<TAnyLightParams>;
  materials?: ReadonlyArray<TMaterialParams>;
  models3d?: ReadonlyArray<TModel3dParams>;
  renderers?: ReadonlyArray<TRendererParams>;
  particles?: ReadonlyArray<TParticlesParams>;
  physics?: TPhysicsParams;
  spatialGrids?: ReadonlyArray<TSpatialGridParams>;
  texts?: ReadonlyArray<TTextParams>;
}>;
