import type { TActorParams } from '@Engine/Actor';
import type { TAnyAudioParams } from '@Engine/Audio';
import type { TAnyCameraParams } from '@Engine/Camera';
import type { TControlsParams } from '@Engine/Controls';
import type { TEnvMapParams } from '@Engine/EnvMap';
import type { TFogParams } from '@Engine/Fog';
import type { TFsmParams } from '@Engine/Fsm';
import type { TAnyIntersectionsWatcherParams } from '@Engine/Intersections';
import type { TAnyLightParams } from '@Engine/Light';
import type { TMaterialParams } from '@Engine/Material';
import type { TModel3dParams } from '@Engine/Models3d';
import type { TParticlesParams } from '@Engine/Particles';
import type { TPhysicsParams } from '@Engine/Physics';
import type { TRendererParams } from '@Engine/Renderer';
import type { TSpatialGridParams } from '@Engine/Spatial';
import type { TTextParams } from '@Engine/Text';

export type TSpaceParamsEntities = Readonly<{
  actors?: ReadonlyArray<TActorParams>;
  audio?: ReadonlyArray<TAnyAudioParams>;
  cameras?: ReadonlyArray<TAnyCameraParams>;
  controls?: ReadonlyArray<TControlsParams>;
  envMaps?: ReadonlyArray<TEnvMapParams>;
  fogs?: ReadonlyArray<TFogParams>;
  fsm?: ReadonlyArray<TFsmParams>;
  intersections?: ReadonlyArray<TAnyIntersectionsWatcherParams>;
  lights?: ReadonlyArray<TAnyLightParams>;
  materials?: ReadonlyArray<TMaterialParams>;
  models3d?: ReadonlyArray<TModel3dParams>;
  renderers?: ReadonlyArray<TRendererParams>;
  particles?: ReadonlyArray<TParticlesParams>;
  physics?: TPhysicsParams;
  spatialGrids?: ReadonlyArray<TSpatialGridParams>;
  texts?: ReadonlyArray<TTextParams>;
}>;
