import type { TActorConfig } from '@/Actor';
import type { TAnyAudioConfig } from '@/Audio';
import type { TAnyCameraConfig } from '@/Camera';
import type { TControlsConfig } from '@/Controls';
import type { TEnvMapConfig } from '@/EnvMap';
import type { TFogConfig } from '@/Fog';
import type { TFsmConfig } from '@/Fsm';
import type { TAnyIntersectionsWatcherConfig } from '@/Intersections';
import type { TAnyLightConfig } from '@/Light';
import type { TMaterialConfig } from '@/Material';
import type { TModel3dConfig } from '@/Models3d';
import type { TParticlesConfig } from '@/Particles';
import type { TPhysicsConfig } from '@/Physics';
import type { TRendererConfig } from '@/Renderer';
import type { TSpatialGridConfig } from '@/Spatial';
import type { TTextConfig } from '@/Text';

export type TSpaceConfigEntities = Readonly<{
  spatialGrids: ReadonlyArray<TSpatialGridConfig>;
  actors: ReadonlyArray<TActorConfig>;
  audio: ReadonlyArray<TAnyAudioConfig>;
  cameras: ReadonlyArray<TAnyCameraConfig>;
  envMaps: ReadonlyArray<TEnvMapConfig>;
  intersections: ReadonlyArray<TAnyIntersectionsWatcherConfig>;
  lights: ReadonlyArray<TAnyLightConfig>;
  materials: ReadonlyArray<TMaterialConfig>;
  models3d: ReadonlyArray<TModel3dConfig>;
  renderers: ReadonlyArray<TRendererConfig>;
  particles: ReadonlyArray<TParticlesConfig>;
  physics: TPhysicsConfig;
  fogs: ReadonlyArray<TFogConfig>;
  fsm: ReadonlyArray<TFsmConfig>;
  texts: ReadonlyArray<TTextConfig>;
  controls: ReadonlyArray<TControlsConfig>;
}>;
