/* AUTO-GENERATED by GenerateLocales.js script — do not edit manually. */
import type { TLocale } from '@Anarchy/i18n/Models';

export const enUs: TLocale = {
  id: 'en-US',
  languageCode: 'en',
  regionCode: 'US',
  englishName: 'English',
  nativeName: 'English',
  dir: 'ltr'
};

export const nlNl: TLocale = {
  id: 'nl-NL',
  languageCode: 'nl',
  regionCode: 'NL',
  englishName: 'Dutch',
  nativeName: 'Nederlands',
  dir: 'ltr'
};

export const ruRu: TLocale = {
  id: 'ru-RU',
  languageCode: 'ru',
  regionCode: 'RU',
  englishName: 'Russian',
  nativeName: 'русский',
  dir: 'ltr'
};

export const arSa: TLocale = {
  id: 'ar-SA',
  languageCode: 'ar',
  regionCode: 'SA',
  englishName: 'Arabic',
  nativeName: 'العربية',
  dir: 'rtl'
};

export const zhHansCn: TLocale = {
  id: 'zh-Hans-CN',
  languageCode: 'zh',
  regionCode: 'CN',
  scriptCode: 'Hans',
  englishName: 'Chinese (Simplified)',
  nativeName: '中文 (简体)',
  dir: 'ltr'
};
