/* AUTO-GENERATED by GenerateLocales.js script — do not edit manually. */

export const enUs = {
  id: 'en-US',
  languageCode: 'en',
  regionCode: 'US',
  englishName: 'English (United States)',
  nativeName: 'English (United States)',
  dir: 'ltr'
};

export const nlNl = {
  id: 'nl-NL',
  languageCode: 'nl',
  regionCode: 'NL',
  englishName: 'Dutch (Netherlands)',
  nativeName: 'Nederlands (Nederland)',
  dir: 'ltr'
};

export const ruRu = {
  id: 'ru-RU',
  languageCode: 'ru',
  regionCode: 'RU',
  englishName: 'Russian (Russia)',
  nativeName: 'русский (Россия)',
  dir: 'ltr'
};

export const arSa = {
  id: 'ar-SA',
  languageCode: 'ar',
  regionCode: 'SA',
  englishName: 'Arabic (Saudi Arabia)',
  nativeName: 'العربية (المملكة العربية السعودية)',
  dir: 'rtl'
};
