/* AUTO-GENERATED by GenerateLocales.js script — do not edit manually. */
import type { TLocale } from '@Anarchy/i18n/Models';

export const enUs: TLocale = {
  id: 'en-US',
  languageCode: 'en',
  regionCode: 'US',
  englishName: 'English (United States)',
  nativeName: 'English (United States)',
  dir: 'ltr'
};

export const nlNl: TLocale = {
  id: 'nl-NL',
  languageCode: 'nl',
  regionCode: 'NL',
  englishName: 'Dutch (Netherlands)',
  nativeName: 'Nederlands (Nederland)',
  dir: 'ltr'
};

export const ruRu: TLocale = {
  id: 'ru-RU',
  languageCode: 'ru',
  regionCode: 'RU',
  englishName: 'Russian (Russia)',
  nativeName: 'русский (Россия)',
  dir: 'ltr'
};

export const arSa: TLocale = {
  id: 'ar-SA',
  languageCode: 'ar',
  regionCode: 'SA',
  englishName: 'Arabic (Saudi Arabia)',
  nativeName: 'العربية (المملكة العربية السعودية)',
  dir: 'rtl'
};

export const zhHansCn: TLocale = {
  id: 'zh-Hans-CN',
  languageCode: 'zh',
  regionCode: 'CN',
  scriptCode: 'Hans',
  englishName: 'Chinese (Simplified, China)',
  nativeName: '中文 (简体, 中国)',
  dir: 'ltr'
};
